/*
 * threemaapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/27/2016
 */

package models_pkg


/*
 * Structure for the custom type CheckRequest
 */
type CheckRequest struct {
    Identities      *[]string       `json:"identities,omitempty" form:"identities,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CheckResponse
 */
type CheckResponse struct {
    CheckInterval   *float64        `json:"checkInterval,omitempty" form:"checkInterval,omitempty"` //TODO: Write general description for this field
    States          *[]float64      `json:"states,omitempty" form:"states,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type MatchRequest
 */
type MatchRequest struct {
    EmailHashes     *[]string       `json:"emailHashes,omitempty" form:"emailHashes,omitempty"` //TODO: Write general description for this field
    MobileNoHashes  *[]interface{}  `json:"mobileNoHashes,omitempty" form:"mobileNoHashes,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type MatchResponse
 */
type MatchResponse struct {
    CheckInterval   *float64        `json:"checkInterval,omitempty" form:"checkInterval,omitempty"` //TODO: Write general description for this field
    Identities      *[]interface{}  `json:"identities,omitempty" form:"identities,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type LinkEmailRequest
 */
type LinkEmailRequest struct {
    Email           *string         `json:"email,omitempty" form:"email,omitempty"` //TODO: Write general description for this field
    Identity        *string         `json:"identity,omitempty" form:"identity,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type LinkEmailResponse
 */
type LinkEmailResponse struct {
    Linked          *bool           `json:"linked,omitempty" form:"linked,omitempty"` //TODO: Write general description for this field
    Token           *string         `json:"token,omitempty" form:"token,omitempty"` //TODO: Write general description for this field
    TokenRespKeyPub *string         `json:"tokenRespKeyPub,omitempty" form:"tokenRespKeyPub,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CheckRevocationKeyRequest
 */
type CheckRevocationKeyRequest struct {
    Identity        *string         `json:"identity,omitempty" form:"identity,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CheckRevocationKeyResponse
 */
type CheckRevocationKeyResponse struct {
    Token           *string         `json:"token,omitempty" form:"token,omitempty"` //TODO: Write general description for this field
    TokenRespKeyPub *string         `json:"tokenRespKeyPub,omitempty" form:"tokenRespKeyPub,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CheckRevocationKeyStage2Request
 */
type CheckRevocationKeyStage2Request struct {
    Response        *string         `json:"response,omitempty" form:"response,omitempty"` //TODO: Write general description for this field
    Nonce           *string         `json:"nonce,omitempty" form:"nonce,omitempty"` //TODO: Write general description for this field
    Token           *string         `json:"token,omitempty" form:"token,omitempty"` //TODO: Write general description for this field
    Identity        *string         `json:"identity,omitempty" form:"identity,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CheckRevocationKeyStage2Response
 */
type CheckRevocationKeyStage2Response struct {
    RevocationKeySet *bool           `json:"revocationKeySet,omitempty" form:"revocationKeySet,omitempty"` //TODO: Write general description for this field
    LastChanged      *string         `json:"lastChanged,omitempty" form:"lastChanged,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type LinkEmailStage2Request
 */
type LinkEmailStage2Request struct {
    Email           *string         `json:"email,omitempty" form:"email,omitempty"` //TODO: Write general description for this field
    Identity        *string         `json:"identity,omitempty" form:"identity,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type LinkEmailStage2Response
 */
type LinkEmailStage2Response struct {
    Linked          *bool           `json:"linked,omitempty" form:"linked,omitempty"` //TODO: Write general description for this field
    Token           *string         `json:"token,omitempty" form:"token,omitempty"` //TODO: Write general description for this field
    TokenRespKeyPub *string         `json:"tokenRespKeyPub,omitempty" form:"tokenRespKeyPub,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreateRequest
 */
type CreateRequest struct {
    PublicKey       *string         `json:"publicKey,omitempty" form:"publicKey,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreateResponse
 */
type CreateResponse struct {
    Token           *string         `json:"token,omitempty" form:"token,omitempty"` //TODO: Write general description for this field
    TokenRespKeyPub *string         `json:"tokenRespKeyPub,omitempty" form:"tokenRespKeyPub,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreateStage2Request
 */
type CreateStage2Request struct {
    PublicKey       *string         `json:"publicKey,omitempty" form:"publicKey,omitempty"` //TODO: Write general description for this field
    Response        *string         `json:"response,omitempty" form:"response,omitempty"` //TODO: Write general description for this field
    Token           *string         `json:"token,omitempty" form:"token,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type CreateStage2Response
 */
type CreateStage2Response struct {
    Identity        *string         `json:"identity,omitempty" form:"identity,omitempty"` //TODO: Write general description for this field
    ServerGroup     *string         `json:"serverGroup,omitempty" form:"serverGroup,omitempty"` //TODO: Write general description for this field
    Success         *bool           `json:"success,omitempty" form:"success,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SetFeaturelevelRequest
 */
type SetFeaturelevelRequest struct {
    Identity        *string         `json:"identity,omitempty" form:"identity,omitempty"` //TODO: Write general description for this field
    FeatureLevel    *float64        `json:"featureLevel,omitempty" form:"featureLevel,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SetFeaturelevelResponse
 */
type SetFeaturelevelResponse struct {
    Token           *string         `json:"token,omitempty" form:"token,omitempty"` //TODO: Write general description for this field
    TokenRespKeyPub *string         `json:"tokenRespKeyPub,omitempty" form:"tokenRespKeyPub,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SetFeaturelevelStage2Request
 */
type SetFeaturelevelStage2Request struct {
    Response        *string         `json:"response,omitempty" form:"response,omitempty"` //TODO: Write general description for this field
    Identity        *string         `json:"identity,omitempty" form:"identity,omitempty"` //TODO: Write general description for this field
    Nonce           *string         `json:"nonce,omitempty" form:"nonce,omitempty"` //TODO: Write general description for this field
    Token           *string         `json:"token,omitempty" form:"token,omitempty"` //TODO: Write general description for this field
    FeatureLevel    *float64        `json:"featureLevel,omitempty" form:"featureLevel,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SetFeaturelevelStage2Response
 */
type SetFeaturelevelStage2Response struct {
    Success         *bool           `json:"success,omitempty" form:"success,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type MatchStage2Request
 */
type MatchStage2Request struct {
    EmailHashes     *[]string       `json:"emailHashes,omitempty" form:"emailHashes,omitempty"` //TODO: Write general description for this field
    MobileNoHashes  *[]interface{}  `json:"mobileNoHashes,omitempty" form:"mobileNoHashes,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type MatchStage2Response
 */
type MatchStage2Response struct {
    CheckInterval   *float64        `json:"checkInterval,omitempty" form:"checkInterval,omitempty"` //TODO: Write general description for this field
    Identities      *[]interface{}  `json:"identities,omitempty" form:"identities,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type GetPubKeyResponse
 */
type GetPubKeyResponse struct {
    Identity        *string         `json:"identity,omitempty" form:"identity,omitempty"` //TODO: Write general description for this field
    PublicKey       *string         `json:"publicKey,omitempty" form:"publicKey,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SetRevocationKeyRequest
 */
type SetRevocationKeyRequest struct {
    Identity        *string         `json:"identity,omitempty" form:"identity,omitempty"` //TODO: Write general description for this field
    RevocationKey   *string         `json:"revocationKey,omitempty" form:"revocationKey,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SetRevocationKeyResponse
 */
type SetRevocationKeyResponse struct {
    Token           *string         `json:"token,omitempty" form:"token,omitempty"` //TODO: Write general description for this field
    TokenRespKeyPub *string         `json:"tokenRespKeyPub,omitempty" form:"tokenRespKeyPub,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SetRevocationKeyStage2Request
 */
type SetRevocationKeyStage2Request struct {
    Response        *string         `json:"response,omitempty" form:"response,omitempty"` //TODO: Write general description for this field
    Identity        *string         `json:"identity,omitempty" form:"identity,omitempty"` //TODO: Write general description for this field
    Nonce           *string         `json:"nonce,omitempty" form:"nonce,omitempty"` //TODO: Write general description for this field
    Token           *string         `json:"token,omitempty" form:"token,omitempty"` //TODO: Write general description for this field
    RevocationKey   *string         `json:"revocationKey,omitempty" form:"revocationKey,omitempty"` //TODO: Write general description for this field
}

/*
 * Structure for the custom type SetRevocationKeyStage2Response
 */
type SetRevocationKeyStage2Response struct {
    Success         *bool           `json:"success,omitempty" form:"success,omitempty"` //TODO: Write general description for this field
}
