/*
 * threemaapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 on 05/27/2016
 */

package o3rest

/** The base Uri for API calls */
const BASEURI string = "https://api.threema.ch"
