/*
 * threemaapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/27/2016
 */

package apiclient_pkg

import "github.com/o3ma/o3rest/models_pkg"

/*
 * Interface for the APICLIENT_IMPL
 */
type APICLIENT interface {
	IdentityCheck(*models_pkg.CheckRequest) (*models_pkg.CheckResponse, error)

	IdentityMatch(*models_pkg.MatchRequest) (*models_pkg.MatchResponse, error)

	IdentityLinkEmail(*models_pkg.LinkEmailRequest) (*models_pkg.LinkEmailResponse, error)

	IdentityCheckRevocationKey(*models_pkg.CheckRevocationKeyRequest) (*models_pkg.CheckRevocationKeyResponse, error)

	IdentityCheckRevocationKeyStage2(*models_pkg.CheckRevocationKeyStage2Request) (*models_pkg.CheckRevocationKeyStage2Response, error)

	IdentityLinkEmailStage2(*models_pkg.LinkEmailStage2Request) (*models_pkg.LinkEmailStage2Response, error)

	IdentityCreate(*models_pkg.CreateRequest) (*models_pkg.CreateResponse, error)

	IdentityCreateStage2(*models_pkg.CreateStage2Request) (*models_pkg.CreateStage2Response, error)

	IdentitySetFeaturelevel(*models_pkg.SetFeaturelevelRequest) (*models_pkg.SetFeaturelevelResponse, error)

	IdentitySetFeaturelevelStage2(*models_pkg.SetFeaturelevelStage2Request) (*models_pkg.SetFeaturelevelStage2Response, error)

	IdentityMatchStage2(*models_pkg.MatchStage2Request) (*models_pkg.MatchStage2Response, error)

	IdentityById(string) (*models_pkg.GetPubKeyResponse, error)

	IdentitySetRevocationKey(*models_pkg.SetRevocationKeyRequest) (*models_pkg.SetRevocationKeyResponse, error)

	IdentitySetRevocationKeyStage2(*models_pkg.SetRevocationKeyStage2Request) (*models_pkg.SetRevocationKeyStage2Response, error)
}

/*
 * Factory for the APICLIENT interaface returning APICLIENT_IMPL
 */
func NewAPICLIENT() APICLIENT {
	return &APICLIENT_IMPL{}
}
